#!/bin/bash

set -o errexit -o nounset -o pipefail

./validate_static
./process_static

remote=root@daniel.micay.dev
active=$(ssh $remote readlink /srv/daniel.micay.dev)

if [[ $active = /srv/daniel.micay.dev_a ]]; then
    target=/srv/daniel.micay.dev_b
else
    target=/srv/daniel.micay.dev_a
fi

echo active is $active
echo target is $target
echo

ssh $remote rm -rf $target
ssh $remote cp -a $active $target
rsync -rpcv --chmod=D755,F644 --delete static_tmp/ $remote:$target
ssh $remote sync -f $target
ssh $remote ln -snf $target /srv/daniel.micay.dev
ssh $remote sync .

sed -i "s|/srv/daniel.micay.dev|$target|" nginx.conf.tmp
rsync -rpcv --chmod=D755,F644 --delete nginx.conf.tmp $remote:/etc/nginx/nginx.conf
ssh $remote sync -f /etc/nginx/nginx.conf
ssh $remote systemctl reload nginx

echo
echo active is now $target
