#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already processing/deploying static files >&2
    exit 1
fi

./process-static $fd

remote=root@daniel.micay.dev
active=$(ssh $remote readlink /srv/daniel.micay.dev)

if [[ $active = /srv/daniel.micay.dev_a ]]; then
    target=/srv/daniel.micay.dev_b
else
    target=/srv/daniel.micay.dev_a
fi

echo active is $active
echo target is $target
echo

ssh $remote "rm -rf $target && cp -a $active $target"
rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate static-tmp/ $remote:$target
ssh $remote "ln -snf $target /srv/daniel.micay.dev && sync /srv/daniel.micay.dev"

echo "root $target;" > nginx-tmp/root_daniel.micay.dev.conf
rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate nginx-tmp/{nginx.conf,mime.types,root_daniel.micay.dev.conf,snippets} $remote:/etc/nginx/
ssh $remote nginx -s reload

echo
echo active is now $target
