#!/bin/bash

set -o errexit -o nounset -o pipefail

./process-static

remote=root@daniel.micay.dev
active=$(ssh $remote readlink /srv/daniel.micay.dev)

if [[ $active = /srv/daniel.micay.dev_a ]]; then
    target=/srv/daniel.micay.dev_b
else
    target=/srv/daniel.micay.dev_a
fi

echo active is $active
echo target is $target
echo

ssh $remote rm -rf $target
ssh $remote cp -a $active $target
rsync -rpcv --chmod=D755,F644 --delete static-tmp/ $remote:$target
ssh $remote sync -f $target
ssh $remote ln -snf $target /srv/daniel.micay.dev
ssh $remote sync /srv/daniel.micay.dev

sed -i "s|/srv/daniel.micay.dev|$target|" nginx-tmp/nginx.conf
rsync -rptcv --chmod=D755,F644 --delete nginx-tmp/nginx.conf $remote:/etc/nginx/nginx.conf
rsync -rptcv --chmod=D755,F644 --delete nginx-tmp/snippets/ $remote:/etc/nginx/snippets
ssh $remote 'sync /etc/nginx/nginx.conf /etc/nginx/snippets/*'
ssh $remote nginx -s reload

echo
echo active is now $target
