#!/bin/bash

set -o errexit -o nounset -o pipefail

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo deploy_static already locked >&2
    exit 1
fi

./process-static $fd

remote=root@daniel.micay.dev
active=$(ssh $remote readlink /srv/daniel.micay.dev)

if [[ $active = /srv/daniel.micay.dev_a ]]; then
    target=/srv/daniel.micay.dev_b
else
    target=/srv/daniel.micay.dev_a
fi

echo active is $active
echo target is $target
echo

ssh $remote "rm -rf $target && cp -a $active $target"
rsync -rpcv --fsync --chmod=D755,F644 --delete static-tmp/ $remote:$target
ssh $remote "ln -snf $target /srv/daniel.micay.dev && sync /srv/daniel.micay.dev"

sed -i "s|/srv/daniel.micay.dev|$target|" nginx-tmp/nginx.conf
rsync -rptcv --fsync --chmod=D755,F644 --delete nginx-tmp/nginx.conf $remote:/etc/nginx/nginx.conf
rsync -rptcv --fsync --chmod=D755,F644 --delete nginx-tmp/snippets/ $remote:/etc/nginx/snippets
ssh $remote nginx -s reload

echo
echo active is now $target
