#!/bin/bash

set -o errexit -o nounset -o pipefail
shopt -s dotglob extglob globstar nullglob

export PATH="$PWD/node_modules/.bin:$PATH"

rm -rf static-tmp
cp -a static static-tmp

for file in static-tmp/**/*.@(json|webmanifest); do
    json_reformat -m < "$file" | sponge "$file"
done

find static-tmp -name '*.css' -exec csso {} -o {} \;
find static-tmp -name '*.js' -exec terser --module -cmo {} {} \;

replace=""
for file in static-tmp/**/*.css static-tmp/**/*.js; do
    hash=$(sha256sum "$file" | head -c 8)
    dest="$(dirname $file)/$hash.$(basename $file)"
    mv "$file" "$dest"
    replace+=";s|/${file#*/}|/${dest#*/}|g"
done

cp nginx/nginx.conf nginx.conf.tmp
sed -i "$replace" static-tmp/**/*.html nginx.conf.tmp

find static-tmp -name '*.html' -exec html-minifier --collapse-whitespace \
    --process-scripts "application/ld+json" --collapse-boolean-attributes \
    --remove-attribute-quotes --remove-comments --remove-empty-attributes \
    --remove-redundant-attributes --remove-script-type-attributes \
    --remove-style-link-type-attributes --sort-attributes --sort-class-name {} -o {} \;

find static-tmp -name '*.xml' -exec xmllint --noblanks {} --output {} \;
find static-tmp -regex '.+\.\(css\|html\|ico\|js\|json\|svg\|txt\|webmanifest\|xml\)' \
    -exec zopfli {} \; -exec touch -r {} {}.gz \; \
    -exec brotli -k {} \;
